# Generated by Django 3.1.5 on 2022-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserental', '0002_houserate_location_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerformfill',
            name='housesize',
            field=models.CharField(max_length=100),
        ),
    ]
